[package]
name = "fit2gpx"
version = "0.1.2"
edition = "2021"

authors = ["Jeromos Kovács <iitsnotme214@proton.me>"]
description = ".fit to .gpx converter"
keywords = ["garmin", "fit", "cli"]
categories = ["command-line-interface"]
repository = "https://github.com/jeromeschmied/fit2gpx-rs"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
fit-rust = "0.1.8"
geo-types = "0.7.13"
gpx = "0.10.0"
time = { version = "0.3.36", default-features = false }
