name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2
      
      - name: Check typos
        if: matrix.os == 'ubuntu-latest'
        uses: crate-ci/typos@v1.29.4

      - name: Build in release mode
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Run cargo fmt
        run: cargo fmt --all --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: fit2gpx_${{ runner.os }}_${{ runner.arch }}
          path: |
              target/release/fit2gpx
              target/release/fit2gpx.exe
